

skillKeyToDisplay = {}
skillKeyToDisplay["athletics"] = "運動"
skillKeyToDisplay["acrobatics"] = "體操"
skillKeyToDisplay["sleight of hand"] = "巧手"
skillKeyToDisplay["stealth"] = "隱匿"
skillKeyToDisplay["arcana"] = "奧秘"
skillKeyToDisplay["history"] = "歷史"
skillKeyToDisplay["investigation"] = "調查"
skillKeyToDisplay["nature"] = "自然"
skillKeyToDisplay["religion"] = "宗教"
skillKeyToDisplay["animal handling"] = "馴獸"
skillKeyToDisplay["insight"] = "洞悉"
skillKeyToDisplay["medicine"] = "醫療"
skillKeyToDisplay["perception"] = "察覺"
skillKeyToDisplay["survival"] = "生存"
skillKeyToDisplay["deception"] = "欺瞞"
skillKeyToDisplay["intimidation"] = "威嚇"
skillKeyToDisplay["performance"] = "表演"
skillKeyToDisplay["persuasion"] = "說服"


speedKeyToDisplay = {}
speedKeyToDisplay["climb"] = "攀爬"
speedKeyToDisplay["burrow"] = "掘地"
speedKeyToDisplay["fly"] = "飛行"
speedKeyToDisplay["swim"] = "游泳"
speedKeyToDisplay["walk"] = "步行"
speedKeyToDisplay["hover"] = "浮空"

damageKeyToDisplay = {}
damageKeyToDisplay["acid"]		 = "強酸"
damageKeyToDisplay["bludgeoning"] = "鈍擊"
damageKeyToDisplay["cold"]		 = "冷凍"
damageKeyToDisplay["fire"]		 = "火焰"
damageKeyToDisplay["force"]		 = "力場"
damageKeyToDisplay["lightning"]	 = "閃電"
damageKeyToDisplay["necrotic"]	 = "黯蝕"
damageKeyToDisplay["piercing"]	 = "穿刺"
damageKeyToDisplay["poison"]		 = "毒素"
damageKeyToDisplay["psychic"]	 = "心靈"
damageKeyToDisplay["radiant"]	 = "光耀"
damageKeyToDisplay["slashing"]	 = "揮砍"
damageKeyToDisplay["thunder"]	 = "雷鳴"
damageKeyToDisplay["acid (conditional)"]			= "強酸（條件）"
damageKeyToDisplay["bludgeoning (conditional)"]	= "鈍擊（條件）"
damageKeyToDisplay["cold (conditional)"]			= "冷凍（條件）"
damageKeyToDisplay["fire (conditional)"]			= "火焰（條件）"
damageKeyToDisplay["force (conditional)"]		= "力場（條件）"
damageKeyToDisplay["lightning (conditional)"]	= "閃電（條件）"
damageKeyToDisplay["necrotic (conditional)"]		= "黯蝕（條件）"
damageKeyToDisplay["piercing (conditional)"]		= "穿刺（條件）"
damageKeyToDisplay["poison (conditional)"]		= "毒素（條件）"
damageKeyToDisplay["psychic (conditional)"]		= "心靈（條件）"
damageKeyToDisplay["radiant (conditional)"]		= "光耀（條件）"
damageKeyToDisplay["slashing (conditional)"]		= "揮砍（條件）"
damageKeyToDisplay["thunder (conditional)"]		= "雷鳴（條件）"


condKeyToDisplay = {}
condKeyToDisplay["blinded"]		 = "目盲"
condKeyToDisplay["charmed"]		 = "魅惑"
condKeyToDisplay["deafened"]		 = "耳聾"
condKeyToDisplay["exhaustion"]	 = "力竭"
condKeyToDisplay["frightened"]	 = "恐懼"
condKeyToDisplay["grappled"]		 = "被擒"
condKeyToDisplay["incapacitated"] = "無力"
condKeyToDisplay["invisible"]	 = "隱形"
condKeyToDisplay["paralyzed"]	 = "麻痹"
condKeyToDisplay["petrified"]	 = "石化"
condKeyToDisplay["poisoned"]		 = "中毒"
condKeyToDisplay["prone"]		 = "伏地"
condKeyToDisplay["restrained"]	 = "束縛"
condKeyToDisplay["stunned"]		 = "震懾"
condKeyToDisplay["unconscious"]	 = "昏迷"
condKeyToDisplay["disease"]		 = "疾病"
