

skillKeyToDisplay = {}
skillKeyToDisplay["athletics"] = "運動"
skillKeyToDisplay["acrobatics"] = "體操"
skillKeyToDisplay["sleight of hand"] = "巧手"
skillKeyToDisplay["stealth"] = "隱匿"
skillKeyToDisplay["arcana"] = "奧秘"
skillKeyToDisplay["history"] = "歷史"
skillKeyToDisplay["investigation"] = "調查"
skillKeyToDisplay["nature"] = "自然"
skillKeyToDisplay["religion"] = "宗教"
skillKeyToDisplay["animal handling"] = "馴獸"
skillKeyToDisplay["insight"] = "洞悉"
skillKeyToDisplay["medicine"] = "醫療"
skillKeyToDisplay["perception"] = "察覺"
skillKeyToDisplay["survival"] = "生存"
skillKeyToDisplay["deception"] = "欺瞞"
skillKeyToDisplay["intimidation"] = "威嚇"
skillKeyToDisplay["performance"] = "表演"
skillKeyToDisplay["persuasion"] = "說服"


speedKeyToDisplay = {}
speedKeyToDisplay["climb"] = "攀爬"
speedKeyToDisplay["burrow"] = "掘地"
speedKeyToDisplay["fly"] = "飛行"
speedKeyToDisplay["swim"] = "游泳"
speedKeyToDisplay["walk"] = "步行"
speedKeyToDisplay["hover"] = "浮空"

damageKeyToDisplay = {}
damageKeyToDisplay["acid"]		 = "強酸"
damageKeyToDisplay["bludgeoning"] = "鈍擊"
damageKeyToDisplay["cold"]		 = "冷凍"
damageKeyToDisplay["fire"]		 = "火焰"
damageKeyToDisplay["force"]		 = "力場"
damageKeyToDisplay["lightning"]	 = "閃電"
damageKeyToDisplay["necrotic"]	 = "黯蝕"
damageKeyToDisplay["piercing"]	 = "穿刺"
damageKeyToDisplay["poison"]		 = "毒素"
damageKeyToDisplay["psychic"]	 = "心靈"
damageKeyToDisplay["radiant"]	 = "光耀"
damageKeyToDisplay["slashing"]	 = "揮砍"
damageKeyToDisplay["thunder"]	 = "雷鳴"
damageKeyToDisplay["acid (conditional)"]			= "強酸（條件）"
damageKeyToDisplay["bludgeoning (conditional)"]	= "鈍擊（條件）"
damageKeyToDisplay["cold (conditional)"]			= "冷凍（條件）"
damageKeyToDisplay["fire (conditional)"]			= "火焰（條件）"
damageKeyToDisplay["force (conditional)"]		= "力場（條件）"
damageKeyToDisplay["lightning (conditional)"]	= "閃電（條件）"
damageKeyToDisplay["necrotic (conditional)"]		= "黯蝕（條件）"
damageKeyToDisplay["piercing (conditional)"]		= "穿刺（條件）"
damageKeyToDisplay["poison (conditional)"]		= "毒素（條件）"
damageKeyToDisplay["psychic (conditional)"]		= "心靈（條件）"
damageKeyToDisplay["radiant (conditional)"]		= "光耀（條件）"
damageKeyToDisplay["slashing (conditional)"]		= "揮砍（條件）"
damageKeyToDisplay["thunder (conditional)"]		= "雷鳴（條件）"


condKeyToDisplay = {}
condKeyToDisplay["blinded"]		 = "目盲"
condKeyToDisplay["charmed"]		 = "魅惑"
condKeyToDisplay["deafened"]		 = "耳聾"
condKeyToDisplay["exhaustion"]	 = "力竭"
condKeyToDisplay["frightened"]	 = "恐懼"
condKeyToDisplay["grappled"]		 = "被擒"
condKeyToDisplay["incapacitated"] = "無力"
condKeyToDisplay["invisible"]	 = "隱形"
condKeyToDisplay["paralyzed"]	 = "麻痹"
condKeyToDisplay["petrified"]	 = "石化"
condKeyToDisplay["poisoned"]		 = "中毒"
condKeyToDisplay["prone"]		 = "伏地"
condKeyToDisplay["restrained"]	 = "束縛"
condKeyToDisplay["stunned"]		 = "震懾"
condKeyToDisplay["unconscious"]	 = "昏迷"
condKeyToDisplay["disease"]		 = "疾病"

baseToDisplay = {}
baseToDisplay["bonus action"] = "附贈動作"
baseToDisplay["saving throw"] = "豁免檢定"
baseToDisplay["cantrip"] = "戲法"
baseToDisplay["opportunity attacks"] = "藉機攻擊"


baseToDisplay["FEYLOST"] = "精界迷失者"
baseToDisplay["FEYWILD VISITOR"] = "妖精荒野來訪者"
baseToDisplay["FEYWILD"] = "妖精荒野"
baseToDisplay["WITCHLIGHT"] = "巫光"

baseToDisplay["Strixhaven"] = "斯翠海文"
baseToDisplay["Lorehold"] = "衡鑑學院"
baseToDisplay["Prismari"] = "粹麗學院"
baseToDisplay["Quandrix"] = "量析學院"
baseToDisplay["Silverquill"] = "銀毫學院"
baseToDisplay["Witherbloom"] = "靡華學院"

baseToDisplay["artisan's tools"] = "工匠工具"
baseToDisplay["alchemist's supplies"] = "鍊金工具"
baseToDisplay["brewer's supplies"] = "釀酒工具"
baseToDisplay["carpenter's tools"] = "木匠工具"
baseToDisplay["cartographer's tools"] = "製圖工具"
baseToDisplay["cobbler's tools"] = "鞋匠工具"
baseToDisplay["cook's utensils"] = "廚師工具"
baseToDisplay["glassblower's tools"] = "玻璃匠工具"
baseToDisplay["jeweler's tools"] = "珠寶匠工具"
baseToDisplay["leatherworker's tools"] = "皮匠工具"
baseToDisplay["mason's tools"] = "泥瓦匠工具"
baseToDisplay["painter's supplies"] = "畫家工具"
baseToDisplay["potter's tools"] = "陶匠工具"
baseToDisplay["smith's tools"] = "鐵匠工具"
baseToDisplay["tinker's tools"] = "修理工具"
baseToDisplay["weaver's tools"] = "織布工具"
baseToDisplay["woodcarver's tools"] = "木雕工具"
baseToDisplay["disguise kit"] = "易容工具"
baseToDisplay["forgery kit"] = "文書偽造工具"
baseToDisplay["gaming set"] = "賭具"
baseToDisplay["herbalism kit"] = "草藥工具"
baseToDisplay["musical instrument"] = "樂器"
baseToDisplay["navigator's tools"] = "領航工具"
baseToDisplay["poisoner's kit"] = "製毒工具"
baseToDisplay["thieves' tools"] = "盜賊工具"
baseToDisplay["tinker's tools"] = "修理工具"
baseToDisplay["vehicles (air)"] = "載具(空中)"
baseToDisplay["vehicles (land)"] = "載具(陸上)"
baseToDisplay["vehicles (sea)"] = "載具(海洋)"
baseToDisplay["vehicles (water)"] = "載具(水上)"
baseToDisplay["type=instrument"] = "type=樂器"

